[package]
name = "clojurust"
version = "0.1.0"
authors = ["ivanpierre <me@ivanpierre.world>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[lib]

[dependencies]
im = { version = "15.0.0", features = [] }
rc = "0.1.1"
bigint = "4.4.3"
lazy_static = "1.4.0"
mut_static = "5.0.0"

