[package]
name = "clojurust"
version = "0.1.0"
authors = ["ivanpierre <me@ivanpierre.world>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
# im = { version = "15.0.0", features = [] }
query_interface = "0.3.5"
rc = "0.1.1"
bigdecimal = "0.2.0"
bigint = "4.4.3"
f128 = "0.2.8"