[package]
name = "clojurust"
version = "0.1.0"
authors = ["ivanpierre <me@ivanpierre.world>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
im-rc = { version = "15.0.0", features = ["proptest", "serde", "arbitrary" ] }
