# Rust format for ClojuRust

blank_lines_upper_bound = 1
# brace_style                  = "AlwaysNextLine"
combine_control_expr = false
wrap_comments        = true
# control_brace_style          = "AlwaysNextLine"
empty_item_single_line       = true
enum_discrim_align_threshold = 20
fn_args_layout               = "Vertical"
fn_single_line               = true
format_code_in_doc_comments  = true
format_macro_matchers        = true
format_strings               = true
imports_layout               = "Vertical"
# license_template_path = "license_template"
match_arm_leading_pipes    = "Always"
match_block_trailing_comma = true
max_width                  = 80
merge_derives              = false
imports_granularity        = "Item"
newline_style              = "Unix"
normalize_comments         = true
normalize_doc_attributes   = true
reorder_impl_items         = true
group_imports              = "StdExternalCrate"
# report_fixme = "Always"
# report_todo = "Always"
struct_field_align_threshold = 30
struct_lit_single_line       = false
type_punctuation_density     = "Compressed"
unstable_features            = true
use_field_init_shorthand     = true
use_small_heuristics         = "Off"
use_try_shorthand            = true
